### ISSUE TITLE
Coordinates flipped between internal and gui  representation

### ISSUE THREAD

**Issue by ArielHorwitz** [imcrazeegamer/YABB#3]
The UI shows  `X, Y` coordinates and the internal representation is `Y, X`. This is particularly confusing while debugging bot behavior, so perhaps it would best to standardize this.

On the one hand it could be easier to flip the axes in the UI, but on the other hand it would probably be more intuitive overall if the internal representation was `X, Y` as well.

**Comment by imcrazeegamer** [comment]
Fliping the internal axis is an option, but it will be very time consuming and would require a complete rework and structure rethink, so what I can offer that is in the scope of the project is that all interfacing between the user and the backend is fliped to
`X, Y`. (all debug stats and API calls)

another thing to consider is the center of the axis and what intuitive to the end-user.

**Comment by ArielHorwitz** [comment]
I think I might have a mistake in my thinking and this is actually a non-issue.. I will try experimenting with the GUI for now.
